In [1]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3], [4,5,6]])

- ndarray 내 data type 은 동일한 type 만 넣을 수 있음. 정수면 정수만 or 문자면 문자
- ndarray 는 메모리에 올라가기 때문에 8 bit or 16 bit integer 형으로 정의하는게 효율적임
  굳이 64bit float 형으로 할 필요없음-->(메모리 많이 먹어...)

axis 0 = 행방향 / axis 1 = 열방향 / axis 2 = Depth

In [16]:
#1차원
list = [1,2,3]

print('list:', list)
print('list type:', type(list))

array1 = np.array(list)
print('array1:', array1)
print('array1 type:', type(array1))
print('array1 shape:', array1.shape)

list: [1, 2, 3]
list type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)


In [17]:
#2차원
array2 = np.array([[1,2,3],[4,5,6]])
print('array2:', array2)
print('array2 type:', type(array2))
print('array2 shape:', array2.shape)

array2: [[1 2 3]
 [4 5 6]]
array2 type: <class 'numpy.ndarray'>
array2 shape: (2, 3)


In [20]:
#2차원 (내포형)
array3 = np.array([[1,2,3]])
print('array3:', array3)
print('array3 type:', type(array3))
print('array3 data type:', array3.dtype)
print('array3 shape:', array3.shape)

array3: [[1 2 3]]
array3 type: <class 'numpy.ndarray'>
array3 type: int64
array3 shape: (1, 3)


In [23]:
#data type 이 다르면 더 큰 type 으로 변함 ( integer < string < float64)
array1 = np.array([1,2,'String'])
print(array1, array1.dtype)

['1' '2' 'String'] <U21


In [25]:
#형변환

array2 = np.array([1,2,3])
array3 = np.array([1.1,2.2,3.3])
array2_float = array2.astype('float64')
array3_int = array3.astype('int')

print(array2_float, array2_float.dtype)
print(array3_int, array3_int.dtype)

[1. 2. 3.] float64
[1 2 3] int64


In [28]:
#Axis 간 Sum
array_sum = np.array([[1,2,3],
                     [4,5,6]])
print(array_sum.sum())
print(array_sum.sum(axis=0))
print(array_sum.sum(axis=1))   

21
[5 7 9]
[ 6 15]
