In [2]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3], [4,5,6]])

- ndarray 내 data type 은 동일한 type 만 넣을 수 있음. 정수면 정수만 or 문자면 문자

- ndarray 는 메모리에 올라가기 때문에 8 bit or 16 bit integer 형으로 정의하는게 효율적임

  굳이 64bit float 형으로 할 필요없음-->(메모리 많이 먹어...)

axis 0 = 행방향 / axis 1 = 열방향 / axis 2 = Depth

In [16]:
#1차원
list = [1,2,3]

print('list:', list)
print('list type:', type(list))

array1 = np.array(list)
print('array1:', array1)
print('array1 type:', type(array1))
print('array1 shape:', array1.shape)

list: [1, 2, 3]
list type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)


In [17]:
#2차원
array2 = np.array([[1,2,3],[4,5,6]])
print('array2:', array2)
print('array2 type:', type(array2))
print('array2 shape:', array2.shape)

array2: [[1 2 3]
 [4 5 6]]
array2 type: <class 'numpy.ndarray'>
array2 shape: (2, 3)


In [20]:
#2차원 (내포형)
array3 = np.array([[1,2,3]])
print('array3:', array3)
print('array3 type:', type(array3))
print('array3 data type:', array3.dtype)
print('array3 shape:', array3.shape)

array3: [[1 2 3]]
array3 type: <class 'numpy.ndarray'>
array3 type: int64
array3 shape: (1, 3)


In [23]:
#data type 이 다르면 더 큰 type 으로 변함 ( integer < string < float64)
array1 = np.array([1,2,'String'])
print(array1, array1.dtype)

['1' '2' 'String'] <U21


In [25]:
#형변환

array2 = np.array([1,2,3])
array3 = np.array([1.1,2.2,3.3])
array2_float = array2.astype('float64')
array3_int = array3.astype('int')

print(array2_float, array2_float.dtype)
print(array3_int, array3_int.dtype)

[1. 2. 3.] float64
[1 2 3] int64


In [28]:
#Axis 간 Sum
array_sum = np.array([[1,2,3],
                     [4,5,6]])
print(array_sum.sum())
print(array_sum.sum(axis=0))
print(array_sum.sum(axis=1))   

21
[5 7 9]
[ 6 15]


- np.arange(10) ==> [0,1,2,3,4,5,6,7,8,9]
- np.zeros((3,2), dtype='int32') ==>
[[0,0],
 [0,0],
 [0,0]]
- np.ones((3,2))
[[1. ,1.],
 [1. ,1.],
 [1. ,1.]]


- reshape(x,y)

 .x 는 axis 0 를 정의 / y는 axis 1을 정의
 
 .x 가 -1 인 경우 axis 1 의 갯수만큼 split 되고 axis 0 이 정해짐 (가변적)
 
 .y 가 null 인 경우 1차원으로 변환됨
 
 .x, y 둘 중 적어도 하나는 정의되어야함. 둘다 -1은 에러

In [4]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


In [9]:
#2차원 reshape
adjusted_array = sequence_array.reshape((2,5))
print(adjusted_array)
print(adjusted_array.dtype)
print(adjusted_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int64
(2, 5)


In [29]:
#2차원 reshape
adjusted_array = sequence_array.reshape((2,-1))
print(adjusted_array)
print(adjusted_array.dtype)
print(adjusted_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int64
(2, 5)


In [13]:
#1차원 reshape
adjusted_array = sequence_array.reshape((-1))
print(adjusted_array)
print(adjusted_array.dtype)
print(adjusted_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64
(10,)
(10,)


In [17]:
#zeros & ones... dtype 정의 없으면 float64가 default
adjusted_array2 = np.zeros((3,2), dtype='int32')
print(adjusted_array2)
print(adjusted_array2.dtype)
print(adjusted_array2.shape)

adjusted_array3 = np.zeros((3,2))
print(adjusted_array3)
print(adjusted_array3.dtype)
print(adjusted_array3.shape)

[[0 0]
 [0 0]
 [0 0]]
int32
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64
(3, 2)


In [21]:
#reshape

adjusted_array4 = adjusted_array.reshape(2,5)
print(adjusted_array4)
print(adjusted_array4.dtype)
print(adjusted_array4.shape)

adjusted_array5 = adjusted_array.reshape(5,2)
print(adjusted_array5)
print(adjusted_array5.dtype)
print(adjusted_array5.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int64
(2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int64
(5, 2)


In [23]:
#2차원 Array로 reshape
adjusted_array6 = adjusted_array4.reshape(-1,1)
print(adjusted_array6)
print(adjusted_array6.dtype)
print(adjusted_array6.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
int64
(10, 1)


In [24]:
#1차원 Array로 reshape
adjusted_array7 = adjusted_array4.reshape(-1,)
print(adjusted_array7)
print(adjusted_array7.dtype)
print(adjusted_array7.shape)

[0 1 2 3 4 5 6 7 8 9]
int64
(10,)


In [30]:
#reshape내 반드시 파라메터 하나는 정의도어야함

adjusted_array7.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#indexing

array1 = np.arange(start=1, stop=9)
#array1 = np.arange(10)

print(array1)
print(array1[2])
print(array1[3])
print(array1[4])

[1 2 3 4 5 6 7 8]
3
4
5


In [58]:
#slicing [start index, end index]... end index -1 값까지 가져옴 (현재 array 한계값을 넘어도 실행은 됨)

print('origin:', array1)
print(array1[0:9])
print(array1[1:9])
print(array1[2:9])
print(array1[0:5])
print(array1[1:5])
print(array1[2:5])

origin: [1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[3 4 5 6 7 8]
[1 2 3 4 5]
[2 3 4 5]
[3 4 5]


In [102]:
#slicing nxdimmention
array_20 = np.arange(20)

array2d = array_20.reshape((4,-1))
print('origin:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:4] \n', array2d[1:3, 0:4])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:3, 1:] \n', array2d[:3, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

origin:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
array2d[0:2, 0:2] 
 [[0 1]
 [5 6]]
array2d[1:3, 0:4] 
 [[ 5  6  7  8]
 [10 11 12 13]]
array2d[1:3, :] 
 [[ 5  6  7  8  9]
 [10 11 12 13 14]]
array2d[:, :] 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
array2d[:3, 1:] 
 [[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]
array2d[:2, 0] 
 [0 5]


In [107]:
#fancy slicing array[[특정index,...], start index: end index]

print('origin: \n', array2d)

print('array[[0,2], 0:3] \n', array2d[[0,2], 0:3])
print('array[[0,1,3], 0:3] \n', array2d[[0,1,3], 0:3])
print('array[[0,1,3]] \n', array2d[[0,1,3]])

origin: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
array[[0,2], 0:3] 
 [[ 0  1  2]
 [10 11 12]]
array[[0,1,3], 0:3] 
 [[ 0  1  2]
 [ 5  6  7]
 [15 16 17]]
array[[0,1,3]] 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [115]:
array1d = np.arange(start=1, stop=10)

print('origin: \n', array1d)
print('array > 5: \n', array1d>5)
print('array[array > 5]: \n', array1d[array1d>5])

array1d[2] = 9

print('value > 5: \n', array1d[array1d>5])

origin: 
 [1 2 3 4 5 6 7 8 9]
array > 5: 
 [False False False False False  True  True  True  True]
array[array > 5]: 
 [6 7 8 9]
value > 5: 
 [9 6 7 8 9]


In [136]:
#sort()...기본 정렬은 오름차순
# np.sort() 는 원본행렬은 그대로 두고 sorting 된 행렬만 반환
# ndarray.sort() 원본행렬을 sorting 하고 None 을 반환함 즉, array.sort() 만으로 실행해도 무방 
# but 반환이 None 이므로 print 등 내부에서 실행하면 None 이 반환됨

origin_arry = np.array([3,1,5,6,8])

sorted_arry = np.sort(origin_arry)
print('origin arry: \n', origin_arry)
print('sorted_arry: \n', sorted_arry)

#sorted_arry2 = origin_arry.sort()
origin_arry.sort()
print('origin arry: \n', origin_arry)
print('Print 내에서 실행 시 origin arry: \n', origin_arry.sort())
#print('sorted_arry2: \n', sorted_arry2)


#내림차순 [::-1]...암기요!
sorted_arry_desc = np.sort(origin_arry)[::-1]
print('내림차순 arry: \n',sorted_arry_desc)

origin arry: 
 [3 1 5 6 8]
sorted_arry: 
 [1 3 5 6 8]
origin arry: 
 [1 3 5 6 8]
Print 내에서 실행 시 origin arry: 
 None
내림차순 arry: 
 [8 6 5 3 1]


In [142]:
# sort in n-dimmension

arry2d = np.array([[1,6],
                  [9,4]])

print('axix0 sorting: \n', np.sort(arry2d, axis=0))
print('axix1 sorting: \n', np.sort(arry2d, axis=1))

print('axix0 sorting_desc: \n', np.sort(arry2d, axis=0)[::-1])
print('axix1 sorting_desc: \n', np.sort(arry2d, axis=1)[::-1])

axix0 sorting: 
 [[1 4]
 [9 6]]
axix1 sorting: 
 [[1 6]
 [4 9]]
axix0 sorting_desc: 
 [[9 6]
 [1 4]]
axix1 sorting_desc: 
 [[4 9]
 [1 6]]


In [153]:
#argsort
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

score_indices = np.argsort(score_array)
print('score argsort: \n', score_indices)

name_sorted = name_array[score_indices]
score_sorted = score_array[score_indices]

print(name_sorted)
print(score_sorted)

#내림차순
score_indices = np.argsort(score_array)[::-1]

name_sorted = name_array[score_indices]
score_sorted = score_array[score_indices]

print(name_sorted)
print(score_sorted)

score argsort: 
 [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']
[98 95 88 84 78]


In [154]:
#선형대수 계산 _ dot...내적구하기 / transpose... (x,y) => (y,x) 로 변환


A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [156]:
A = np.array([[1, 3],
              [9, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 9]
 [3 4]]


- 통상 2차원 컨트롤은 PANDAS 가 효율적이고 편함

- but 3차원으로 들어가면 필수적으로 Numpy 로 컨트롤을 해야함.